### ISSUE TITLE
The app is not updated in f-droid

### ISSUE THREAD

**Issue by KOLANICH** [JohnMH/BoogDroid#18]

**Comment by JohnMH** [comment]
I know why: My name change. Ouch.

**Comment by holgersson32644** [comment]
Any progress here? :-)

**Comment by albfan** [comment]
@JohnMH if you grant me permissions I can update the app

**Comment by JohnMH** [comment]
@albfan What do you need?

**Comment by albfan** [comment]
Don't know is the process. Seems I need to open a request for packaging

https://gitlab.com/fdroid/rfp

But I suppose it should have a signature or similar to be accepted. Really don't know

**Comment by JohnMH** [comment]
I'll just go and open an issue against the package that's already listed. The issue isn't that they don't have it packaged, it's that the code for updating was checking against a repo that no longer exists, at my old name.

**Comment by albfan** [comment]
Can you link here an old issue with the last time you request for package?

**Comment by JohnMH** [comment]
I don't remember doing that through their issue tracking, but if you wouldn't mind opening an issue against fdroiddata on their GitLab.com repo, I'd appreciate it.. Currently, I do not have access to my GitLab account.

**Comment by JohnMH** [comment]
I have opened an issue against fdroiddata. Closing, follow up at https://gitlab.com/fdroid/fdroiddata/issues/1066 or reply here.

**Comment by albfan** [comment]
Better to see it at least one time from you

**Comment by IzzySoft** [comment]
The issue at F-Droid is stuck, waiting for a new release here which includes the fix made (reverting the change of package ID). Any chance that will be done soon?

**Comment by bene64** [comment]
We've just closed https://gitlab.com/fdroid/fdroiddata/-/issues/1066, as we can't do anything without a new tag here.

Please feel free to contact us, if the tag gets added.
